# ARG DEFAULT_PORT=3000
### Stage 1 ###
FROM node:20-alpine

WORKDIR /app

COPY package.json ./

RUN npm install
COPY . .
RUN npm run build
# ENV PORT $DEFAULT_PORT

EXPOSE 3000

CMD [ "npm", "run", "start" ]