# ARG DEFAULT_PORT=3000
### Stage 1 ###
FROM node:20-alpine

WORKDIR /app

COPY package.json ./

RUN npm install
# RUN npm run build

COPY . .

# ENV PORT $DEFAULT_PORT

EXPOSE 3000

CMD [ "npm", "run", "dev" ]