version: "3.8" # Use the latest version if possible
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres # Use Docker secrets or env files
      POSTGRES_DB: db_postgres
      TZ: "GMT"
      PGTZ: "GMT"
    ports:
      - "5431:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  frontend:
    container_name: frontend
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - NEXTAUTH_URL=http://localhost:3000
      - NEXT_SERVER_URL=http://backend:3900 # Updated to use backend service name
      - NEXTAUTH_SECRET=resturant-application
      - AUTH_SECRET=AwZLoFadutg7Efmiz5OhAGEzZOSsVQOySI8eTBarztM
    restart: always
    volumes:
      - ./client:/app
    depends_on:
      - backend

  backend:
    container_name: backend
    build: ./server
    ports:
      - 3900:3900
    volumes:
      # - ./server/app/node_modules
      - ./server:/app
    # env_file:
    #   - .env
    environment:
      DB_TYPE: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres # Use Docker secrets or env files
      DB_DATABASE: db_postgres
      DB_HOST: postgres
      DB_PORT: 5432
    depends_on:
      - postgres

volumes:
  pg_data:
