services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres # Use Docker secrets or env files
      POSTGRES_DB: db_postgres
      TZ: "GMT"
      PGTZ: "GMT"
    ports:
      - "5431:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  frontend:
    container_name: frontend
    build:
      dockerfile: dockerfile
      context: ./client
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env.local
    restart: always
    volumes:
      - /client/app/node_modules
      - ./client:/app
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      dockerfile: dockerfile
      context: ./server
    ports:
      - 3900:3900
    volumes:
      - /server/app/node_modules
      - ./server:/app
    env_file:
      - ./server/.env
    depends_on:
      - postgres

volumes:
  postgresql_data:
