services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres # Use Docker secrets or env files
      POSTGRES_DB: db_postgres
      TZ: "GMT"
      PGTZ: "GMT"
    ports:
      - "5431:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - main-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - main-network
  frontend:
    container_name: frontend
    build:
      dockerfile: dockerfile
      context: ./client
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env.local
    restart: always
    volumes:
      - /client/app/node_modules
      - ./client:/app
    depends_on:
      - backend
    networks:
      - main-network
  redis:
    container_name: redis-server
    image: redis/redis-stack:latest
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/var/lib/redis-stack
    environment:
      - RADIS_ARGS=--save 900 1
    networks:
      - main-network
  backend:
    container_name: backend
    build:
      dockerfile: dockerfile
      context: ./server
    ports:
      - 3900:3900
    volumes:
      - /server/app/node_modules
      - ./server:/app
    env_file:
      - ./server/.env
    depends_on:
      - postgres
      - redis
    networks:
      - main-network

networks:
  main-network:
    driver: bridge

volumes:
  postgresql_data:
  redis_data:
