services:
  postgres:
    image: postgres:17-alpine
    container_name: ecommerce_postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: gowtampaul1995@
      POSTGRES_DB: ecommerce_db
      TZ: "GMT"
      PGTZ: "GMT"
    ports:
      - "5544:5432" # external:internal
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - main_network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=gowtampaul0@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=gowtampaul1995@
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - main_network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    container_name: server_app
    restart: always
    env_file:
      - ./server/.env.production
    ports:
      - "4400:4400"
    volumes:
      - ./server/public/uploads:/app/public/uploads
      - ./server:/app
    depends_on:
      - postgres
    networks:
      - main_network
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    container_name: client_app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env.local
    environment:
      - NEXTAUTH_TRUST_HOST=true
    # expose:
    #   - "80"
    depends_on:
      - server
    networks:
      - main_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    # - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./server/public/uploads:/app/public/uploads
    # - ./nginx/certbot/conf:/etc/letsencrypt
    # - ./nginx/certbot/www:/var/www/certbot
    depends_on:
      - client
      - server
    networks:
      - main_network

# certbot:
#   image: certbot/certbot
#   container_name: inventory_certbot
#   volumes:
#     - ./nginx/certbot/conf:/etc/letsencrypt
#     - ./nginx/certbot/www:/var/www/certbot
#   # command: >
#   #   "sleep 10 &&
#   #    certbot certonly --webroot --webroot-path=/var/www/certbot
#   #    --email gowtam.semicolonit@gmail.com --agree-tos --no-eff-email
#   #    -d inventory.semicolonit.com -d www.inventory.semicolonit.com"

networks:
  main_network:
    driver: bridge

volumes:
  postgres_data:
