import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "./style.css";
import "antd/dist/reset.css";
import StoreProvider from "@/redux/storeProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "../lib/authOption";
import AuthProvider from "../lib/SessionProvider";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/scrollbar";
import "swiper/css/autoplay";
import CartSync from "@/components/CartSync";

const poppinsFont = localFont({
  src: [
    // Poppins Font Variants
    {
      path: "../fonts/Poppins/Poppins-Black.woff2",
      weight: "900",
      style: "normal",
    },
    {
      path: "../fonts/Poppins/Poppins-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../fonts/Poppins/Poppins-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../fonts/Poppins/Poppins-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../fonts/Poppins/Poppins-Regular.woff2",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${poppinsFont.variable}`}
      >
        <AuthProvider session={session}>
          <StoreProvider>
            <AntdRegistry>
              <CartSync />
              {children}
            </AntdRegistry>
          </StoreProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
