import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "swiper/css";
import StoreProvider from "@/redux/storeProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "../lib/authOption";
import AuthProvider from "../lib/SessionProvider";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import 'react-multi-carousel/lib/styles.css';
// import 'antd/dist/antd.css'
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={`${inter.className}`}>
        <AuthProvider session={session}>
          <StoreProvider>
            <AntdRegistry>{children}</AntdRegistry>
          </StoreProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
