import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/redux/storeProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "../lib/authOption";
import AuthProvider from "../lib/SessionProvider";

import {
  CredentialInput,
  CredentialsConfig,
} from "next-auth/providers/credentials";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  interface authOptionsInterface {
    providers: CredentialsConfig<Record<string, CredentialInput>>[];
    pages: {
      signIn: string;
      signOut: string;
      error: string;
      verifyRequest: string;
      newUser: string;
    };
    secret: string | undefined;
    session: {};
    callbacks: {};
  }

  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={`${inter.className} bg-white`}>
        <AuthProvider session={session}>
          <StoreProvider>{children}</StoreProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
