import { ThemeProvider } from "next-themes";
import "../styles/globals.css";
import { Inter } from "next/font/google";
import Darkmode from "@/components/DarkMode";
import Header from "@/components/Header";
import Widget from "@/components/front-end/Wiget";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${inter.className} `} suppressHydrationWarning={true}>
        <main>
          <Header />
          {children}
          <Widget />
          <Footer />
        </main>
      </body>
    </html>
  );
}
