ARG DEFAULT_PORT=3900
### Stage 1 ###
FROM node:20-alpine3.20

WORKDIR /app

COPY package.json ./

RUN npm install
# RUN npm run build

COPY . .

ENV PORT $DEFAULT_PORT

EXPOSE $PORT

CMD [ "npm", "run", "dev" ]