import { Metadata } from "next";
import dynamic from "next/dynamic";

const MainDashboard = dynamic(
  () => import("@/components/dashboard/dashboard/Dashboard")
);
export const metadata: Metadata = {
  title: "Next.js Dashboard",
  description: "Generated by Next.js Dashboard",
};

export default function Page() {
  return <MainDashboard />;
}
