export enum NotificationType {
  // Order-Related Notifications
  Order = 'Order', // General fallback
  OrderPlaced = 'OrderPlaced',
  OrderShipped = 'OrderShipped',
  OrderDelivered = 'OrderDelivered',
  OrderCanceled = 'OrderCanceled',
  AdminNewOrder = 'ADMIN_NEW_ORDER',
  AdminPaymentFailed = 'ADMIN_PAYMENT_FAILED',
  AdminOrderCanceled = 'ADMIN_ORDER_CANCELED',
  AdminLowStock = 'ADMIN_LOW_STOCK',
  AdminHighValueOrder = 'ADMIN_HIGH_VALUE_ORDER',
  AdminRefundRequest = 'ADMIN_REFUND_REQUEST',
  AdminRefundApproved = 'ADMIN_REFUND_APPROVED',
  AdminSettlementCompleted = 'ADMIN_SETTLEMENT_COMPLETED',
  PromotionalMarketing = 'PromotionalMarketing',
  CouponApplied = 'CouponApplied',
  CouponExpired = 'CouponExpired',
  NewOffer = 'NewOffer',
  WishlistPriceDrop = 'WishlistPriceDrop',
  ProductBackInStock = 'ProductBackInStock',
  ProductLowStock = 'ProductLowStock',
  ReviewRequest = 'ReviewRequest',
  ReviewSubmitted = 'ReviewSubmitted',
  AdminReviewCreated = 'AdminReviewCreated',
  AdminReviewReported = 'AdminReviewReported',
  SystemAlert = 'SystemAlert',
  ServerDown = 'ServerDown',
  HighTraffic = 'HighTraffic',
  PaymentGatewayError = 'PaymentGatewayError',
  SmsEmailFailed = 'SmsEmailFailed',
  CronJobFailed = 'CronJobFailed',
  UserAccount = 'UserAccount',
  ReviewFeedback = 'ReviewFeedback',
  CustomerSupport = 'CustomerSupport',
  WishlistSubscription = 'WishlistSubscription',

  // Custom User Notifications
  UserRegistration = 'UserRegistration',
  UserLogin = 'UserLogin',
  PasswordChanged = 'PasswordChanged',
  ForgotPassword = 'ForgotPassword',
  NewsletterSubscription = 'NewsletterSubscription',
  Verification = 'Verification',
  PaymentSuccess = 'PaymentSuccess',
  PaymentFailed = 'PaymentFailed',
  RefundInitiated = 'RefundInitiated',
  RefundCompleted = 'RefundCompleted',
  CodVerification = 'CodVerification',
  // Admin Notifications
  AdminNewUser = 'ADMIN_NEW_USER',
  AdminSecurityAlert = 'ADMIN_SECURITY_ALERT',
}
