name: crojob workflow head

on: 
  schedule:
    - cron: '*/5 * * * *' # runs in every 5 minutes
jobs:
  cronjob-workflow:
    runs-on: ubuntu-latest
    
    steps:
      - name: cronjob step
        run: echo 'this is cronjob workflow' 