name: value-pass workflow

on:
  push:
    paths:
      - "server/**"

jobs:
  value-pass-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: first value-pass job
        run: |
          echo "learn conditinal job"
